### ISSUE TITLE
Argo

### ISSUE THREAD

**Issue by ET-NCMP** [ET-NCMP/et-ncmp.github.io#21]
Argo has emerged as the validation data set of choice. ERSSTv5 incorporates Argo though, which leaves nothing with which to validate it.

**Comment by lizkent** [comment]
This recent paper describing a validation of satellite SST using a range of in situ data sources suggests that the sparseness of Argo observations means that they are less effective than the less accurate, but more numerous, drifting buoy temperatures for detecting discontinuities in the satellite data:

Berry, D.I.; Corlett, G.K.; Embury, O.; Merchant, C.J. Stability Assessment of the (A)ATSR Sea Surface Temperature Climate Dataset from the European Space Agency Climate Change Initiative. Remote Sens. 2018, 10, 126.

**Comment by ET-NCMP** [comment]
Added some words on this in the assessment of bias adjustment section.
